### PR TITLE
Added flag 'userID'.

### LINKED ISSUE #40: Can Pagelist display login names (usernames) instead of full names?
It seems that Pagelist can only display full name if setting/flag 'showuser' is on. Can it also display login names? Maybe there is a way to tweak some code to do that?

### PR DESCRIPTION
**Pull request by lpaulsen93**
If the flag is set then 'showuser' will display the user-ID instead of the full user name. If the flag is not set/not present then 'showuser' will behave like usual and display the full names. Closes #40.

Worked good in my test page. Use of metadata is as per documented at https://www.dokuwiki.org/devel:metadata, so should work.

Please review and merge if ok. Thanks.

### CODE REVIEW

**Comment by michitux** [comment]
I would actually prefer to display the user as it is done in DokuWiki itself which makes it even possible to display a link in current versions of DokuWiki. See also dokufreaks/plugin-include#154.

**Comment by LarsGit223** [comment]
Thanks for the hint, I like the idea.

Unfortunately it looks like the meta information does only store full names in some cases so I can't use that as an input to function userlink().

Plugin pagelist allows to configure that the creator or the contributors should be displayed. I don't know how to retrieve the user names for both cases.

**Comment by michitux** [comment]
According to the [metadata documentation](https://www.dokuwiki.org/devel:metadata) the `user` property should store the creator and `contributor` should be a list `user ID ⇒ full name`, so using the keys (`array_keys()`) here should work. The code [here](https://github.com/splitbrain/dokuwiki/blob/master/inc/changelog.php#L89) also seems to work as documented. Does this solve the problem?

**Comment by LarsGit223** [comment]
Ok, of course (should have re-read the documentation myself).

I threw away the 'userID' flag and added two new config options for 'showuser'. In that way an update will not influence existing installations.

**Comment by michitux** [comment]
I wonder if we shouldn't just re-use the existing options and do not offer the old variants anymore. I know that not influencing existing installations is also nice, but actually this also means that no user will ever see the new feature unless he/she changes the settings. Nevertheless I think this is also good enough as it is, we can also still drop the old options again later.

**Comment by LarsGit223** [comment]
Hmmm...I am undecided about this. It would be nice to know what the users of the plugin think. But as you said maybe we just leave it as it is for now and then throw away the old options in a future release. Should we mark them as deprecated by e.g. appending "(deprecated)" to the options text?

**Comment by LarsGit223** [comment]
@michitux:
Any news on this/did you make up your mind?
I will leave the decision up to you to throw away the old options or not. Just let me know your decision and then we can merge it right away or I change the options.

I would like to get this finished.

**Comment by michitux** [comment]
Okay, then let's leave the options as you prepared them but change the default from 1 to 3, so users get the new behavior but can change it back of they prefer it.

**Comment by michitux** [comment]
One thing I've just noticed: when a user uses the `user ` flag, he will always get 1 as configuration value. This is a bit unfortunate. However the old option has one advantage: it most probably works better in wikis where users have been deleted or where user information is complicated to get (though the old revisions lists in DokuWiki itself will have the same problem). I think it's therefore also a question how we can adapt the flags. If there is no good solution for flags, we should probably drop the old options in order to not to make the flags too complicated.

**Comment by LarsGit223** [comment]
I just had a look at an older release. All flags simply have the problem that they are just set to **true**. So for the flag **user** this was already bad before because you can't differ between the options hide, creator and contributors.

I think the flags should enable the user to have the columns different from what is configured but it doesn't make much sense if the can't choose from all options. Maybe we should allow something like **user=option**. With a default value of 1 (like today) if we only find **user**.

**Comment by Klap-in** [comment]
I prefer moving to the newest format. Also in /conf/default.php selecting option 3 is fine for me.

**Pull request merged**
